### PR TITLE
Client issue with OVER_QUERY_LIMIT

### PR DESCRIPTION
**Pull request by nerfologist**
Hi,
this PR is related to issue #6.

I added a **failing test** which reproduces the issue I'm facing with the `GoogleClient` component.

Thanks for this great library 👍 
HTH

### CODE REVIEW

**Comment by nerfologist** [comment]
Hi, I just rebased on top of master; I was hoping for this test to pass but apparently it's still failing with the following reason:

```
       expected no Exception, got #<ArgumentError: wrong number of arguments (given 8, expected 0)> with backtrace:
         # ./lib/googlemaps/services/client.rb:102:in `request'
         # ./lib/googlemaps/services/client.rb:170:in `rescue in request'
         # ./lib/googlemaps/services/client.rb:150:in `request'
```
It seems that the retried `self.request` in the `rescue` call at line 170 is still failing but for the life of me I cannot figure out why this method will not accept its arguments and fail claiming it needs no arguments.

Do you have an idea?

Thanks in advance 👍

**Comment by amrfaissal** [comment]
Yes because your PR uncovered another bug in `self.request()` which has to do with named parameters. If I remember correctly, in Ruby 2.1 we need to specify the name of the parameter when passing arguments. So `self.request("/path/to/something", {})` won't work unless we name the parameters: `self.request(url: "/path/to/something", params: {})`.

I'm already working on a fix. Hope this isn't a blocking issue for you.

**Comment by nerfologist** [comment]
Not at all. Thanks for your insight! Glad to contribute.

**Comment by amrfaissal** [comment]
I've merged your changes manually with some tweaks 😄

**Comment by nerfologist** [comment]
Glad I could help! Thanks for your great work 👍

**Pull request closed without merging**
